### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-mailgun-source#1]
**Requirements**
- Enable pagination to traverse
- Pull in all records for:
  - [ ] [Events](https://documentation.mailgun.com/api-events.html#events) (default to pull time range of 1 day prior to workflow running)
  - [ ] [Domains](https://documentation.mailgun.com/api-domains.html)
  - [ ] [Stats](https://documentation.mailgun.com/api-stats.html#stats)
  - [ ] [Mailing List](https://documentation.mailgun.com/api-mailinglists.html)
- Register and test [Webhooks](https://documentation.mailgun.com/api-webhooks.html)

**Relevant Links**
https://documentation.mailgun.com/api_reference.html

**Comment by dansweet1** [comment]
1/6/17- Obtained api access tokens on Friday. Worked with Noah to set up boiler plate project.
1/9/17- Working on Mailing List then moving onto Events once data is retrieved.

**Comment by dansweet1** [comment]
1/9/17 Worked with Alois to fix admin issues on my machine which in turn cleared up testing issues and installation of Mocha, Nock, and Chai (they now work and tests run). Began to Debug the Events and Mailing list last night. 
1/10/17 Going to reach out to Mike or Trong to ensure I am using Promises correctly, tips or tricks they might have while debugging, and ensure I am doing what is expected in terms of development. @benjamingregory let me know if this is permissible as a SU update or is too verbose.

**Comment by dansweet1** [comment]
1/10/17 had to refactor my integration a bit. Was missing some key modules from initial installation that disallowed me to run tests. Worked with Collen to integrate fixtures.

**Comment by dansweet1** [comment]
1/11/17 Finishing stubbing out test fixtures and wrap up all the requirements. Ensure pagination is working.

**Comment by dansweet1** [comment]
1/12/17 Working on Pagination and Webhooks. All tests are passing for:  
 Events
 Domains
 Stats
 Mailing List

**Comment by dansweet1** [comment]
1/18/17 (Sorry forgot to do this for the past..4 days)
Friday and Tuesday I worked on getting HTTP auth instead of O-auth with Alois' help got it running. 
Yesterday I was having troubles getting Airflow up and running due to the fact that I had a local instance using the same port "27017" as Airflow tried to spin up. 

Today Trong showed me how to build my Docker image, how to create a DAG and a config in MongoChef. Now I am running my tests without Nock to ensure I am getting Data back from Mailgun. Need to add comments to my code as well per my meeting with Mike today.

**Comment by dansweet1** [comment]
1/19/17
Removed unnecessary methods/tests/fixtures. Working on getting events working. Updated api key to use astronomer mailgun credentials. I will not be in tomorrow as I am getting ENGAGED!! But will be signed on Sunday to continue working.

**Comment by benjamingregory** [comment]
Hey @dansweet1  -- Can you provide on an update on this? Seems like you should be close to making a PR, yes?

**Comment by dansweet1** [comment]
@benjamingregory After removing the unnecessary methods on Thursday I started testing without Nock and on the Stats API I am getting  'StatusCodeError: 400 - {"message":"please provide at least one event"}' which should be an easy fix. That's the only piece left I believe before PR.

**Comment by benjamingregory** [comment]
@dansweet1 Please provide an update on this.

**Comment by dansweet1** [comment]
Submitting Pull request. Moving to issue we spoke about yesterday.

**Comment by benjamingregory** [comment]
@dansweet1 When you submit a PR, move the active issue (this one) to done until the PR is reviewed and any changes are recommended.

**Comment by dansweet1** [comment]
Ok will do. Sorry for the mixup!
